config/routes.rb
Rails.application.routes.draw do
  # get "/", to:
  # verb -> path -> controller_name -> controller action
  root to: "flats#index"
  get "/flats/:id", to: "flats#show", as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :set_flats, only: [:index, :show]

  def index
    # @flats = Flat.all
  end

  def show
    @id = params[:id].to_i
    @flat = @flats.find {|flat|  flat["id"] == @id}
    # @flat = Flat.find(params[:id])
  end

  private

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
<ul>
  <% @flats.each do |flat| %>
    <li><%= link_to flat["name"], flat_path(flat["id"]) %></li>
    <li><%= flat["price"] %> <%= flat["priceCurrency"] %></li>
    <br>
  <% end %>
</ul>

 <!-- <%#= link_to "home", root_path %> -->

app/views/flats/show.html.erb
<h1><%= @flat["name"] %></h1>
<%= link_to "home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbCloneStatic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>